### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by Ousmane-d** [ps-actions-sandbox/ActionsFundamentals#19]
My name is Ousmane, I am a Security Network engineer
GitHub Experience : junior 
CI/CD tools : I've been working with Azure Devops / YAML for 3 years now and I expect to learn some good skills with GitHub

**Comment by michaelcontento** [comment]
Hi Ousmane,

I think your comment was supposed to be part of the first question (**❓ What is your experience with GitHub?**) in an actual GitHub Actions training, right? 😄 

So I will close this issue here, as this is the wrong place. Feel free to re-open this issue if I got this wrong.

All the best 👋
